### ISSUE TITLE
Device Descriptor semantics insufficient

### ISSUE THREAD

**Issue by paalsteek** [mysmartgrid/hexabus#151]
The device descriptor is currently interpreted as bit field for the EIDs 0 to 31. That way it is not possible to see whether EID 32 (and other EIDs > 31) exists or not.

In the beginning the device descriptor was meant to be interpreted as the EIDs 1 to 32. This was changed for some reason I don't know.

**Comment by LongHairedHacker** [comment]
Fixed along with #153
