### ISSUE TITLE
Fix EID enumeration scheme

### ISSUE THREAD

**Issue by myeisha** [mysmartgrid/hexabus#153]
Our current enumeration scheme is somewhat broken. By querying EIDs 32N we can enumerate the entire device, but that's pretty much useless since it takes prohibitively long.

Suggestion: encode the next descriptive EID associated with the next used non-descriptive EID into a queried discriptor packet. Say EID 3 and 103 are used, then querying EID 0 should reply with a bitmask for itself and EID 3 (i.e. 9) and 96, which could describe 103 when queried.

**Comment by ravinrabbid** [comment]
Endpoints are now enumerated using endpoint properties, see d557ad0.
