### ISSUE TITLE
Compiler should be able to treat several devices as a group

### ISSUE THREAD

**Issue by gonium** [mysmartgrid/hexabus#167]
Scenario: I want to be able to specify an action if  one switch in a group of devices is triggered, for example one switch in the ground floor.

 * The compiler should be able to generate a list of devices
 * The statemachine interpreter on the devices should be able to check a condition against that list

**Comment by ghost** [comment]
Done in 5d683b904cf340ce9e6ac67d624c8e734b4921ba
