### ISSUE TITLE
Greyed out sensor boxes

### ISSUE THREAD

**Issue by wintermutepi** [mysmartgrid/hexabus#198]
At the moment, all my sensors (Sockets+) are displayed by the Hexabus base station as greyed out boxes with measurements of 0. What causes this behaviour - is it intentional?
![hexabus basisstation02](https://f.cloud.github.com/assets/1478149/1542165/f33919d6-4d42-11e3-8b77-f3eaeea95c5f.png)

**Comment by LongHairedHacker** [comment]
Fixed
