### ISSUE TITLE
Shouldn't the State Machine be able to send packets?

### ISSUE THREAD

**Issue by wookinger** [mysmartgrid/hexabus#65]
I'd like to be able to set the date and time of other hexabus boards triggered by a state machine condition.
Therefore I need to send packets as action of a transition.

Example:
Button is pressed -> switch current time

This might also be necessary, if we want to build some kind of DCF77 hexabus clock setting mechanism.

**Comment by ghost** [comment]
The state machine has had memory for this kind of thing for a while now and caching is really easy.
