### ISSUE TITLE
State machine should be able to query endpoints

### ISSUE THREAD

**Issue by eBrnd** [mysmartgrid/hexabus#97]
Today we decided that the state machine should be able to request data from endpoints.

Imagine this scenario: The user pushes a button, but in order to find out what action to execute the state machine needs additional data from a sensor which has not been broadcastet yet, changes quickly or is complex enough that "caching" it in the state machine is too resource consuming.

In this case, the state machine should be able to send out a QUERY packet to the device. There should be two types of request: One which triggers an INFO _broadcast_, and one which triggers an INFO packet sent to the requester _directly_ (but works over the borders of the broadcast domain since "direct" packets can be routed).

**Comment by LongHairedHacker** [comment]
The new statemachine has memory. It can save values from broadcasts.
